// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.team5883.commands.drivetrain;
import edu.wpi.first.wpilibj.command.Command;
import frc.team5883.robot.Robot;

/**
 *
 */

public class Drive extends Command {
 
    public Drive() {

    	requires(Robot.driveTrain);
    }

    protected void initialize() {
    	Robot.driveTrain.resetSpeed();
    }

    protected void execute() {
    	Robot.driveTrain.driveWithJoysticks();
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    	Robot.driveTrain.stopDrive();
    }

    protected void interrupted() {
    	end();
    }
}
